### ISSUE TITLE
Wiki for detailed documentation

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/authorization#52]
How about moving the README content to wiki pages and providing only an overview of the features as well as a wiki link in the README?

> GitHub Wikis are a place in your repository where you can share long-form content about your project, such as how to use it, how it's been designed, manifestos on its core principles, and so on. Whereas a README is intended to quickly orient readers as to what your project can do, wikis can be used to provide additional documentation.

**Comment by mmnosek** [comment]
I think that according to the quote above it's good idea. @warpech @joozek78 WDYT?

**Comment by warpech** [comment]
We have too many places where to look for information. I'd rather keep it in the repo. 

By keeping the docs in the repo, as a bonus you get the version of the docs tied up with the version of the library.

Changes to the docs can be accepted as PRs.

**Comment by joozek78** [comment]
> By keeping the docs in the repo, as a bonus you get the version of the docs tied up with the version of the library.

I like that property.

**Comment by mmnosek** [comment]
I think we can close it. The decision is that we will keep the track of readme in the repo, as in our other projects.
