### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/authorization#53]
Please add a small section about which apps u need to run in order to test the authorization (portal, sign-in, user admin,..).

**Comment by jwillmer** [comment]
@mmnosek

**Comment by mmnosek** [comment]
## How to start
Minimum reasonable configuration to start playing around with this library is to use sample [apps provided by Starcounter](https://github.com/StarcounterApps):

1. [Launcher](https://github.com/StarcounterApps/Launcher) - provides a common UI frame (menu)
2. [UserAdmin](https://github.com/StarcounterApps/UserAdmin) - allows to create system users
3. [SignIn](https://github.com/StarcounterApps/SignIn) - authenticates user with a username and password
4. [People](https://github.com/StarcounterApps/People) - gives a way to organize people into groups that may be used with this library

App set above is the sample that allows dealing with users and groups in Simplified data model provided with Starcounter. Thanks to that you will be able to apply instructions above and build a working solution.

cc @joozek78 @jwillmer do you think something like that will be good?

**Comment by mmnosek** [comment]
Readme updated, closing! If you have any more ideas how to improve the documentation, please create separate issues :)
